export const EMPLOYEES_LOADED = 'Employees/EMPLOYEES_LOADED';
export const EMPLOYEES_LOADING = 'Employees/EMPLOYEES_LOADING';
export const EMPLOYEES_LOADING_ERROR = 'Employees/EMPLOYEES_LOADING_ERROR';
export const EMPLOYEES_ADDED = 'Employees/EMPLOYEES_ADDED';